import type React from 'react';
import type { CartItem, Product, Category, Customer } from '@/types';

export interface Design7POSLayoutProps {
  cart: CartItem[];
  onAddToCart: (product: Product, customPrice?: number) => void;
  onUpdateQty: (productId: string, qty: number) => void;
  onRemoveFromCart: (productId: string) => void;
  onClearCart: () => void;
  onEditPrice?: (productId: string, newPrice: number) => void;
  saleSummary: {
    subtotal: number;
    discountAmount: number;
    total: number;
    tvaAmount?: number;
  };
  products: Product[];
  allProducts?: Product[];
  categories: (Category | { id: string; name: string } | string)[];
  selectedCategory: string;
  onSelectCategory: (categoryId: string) => void;
  favoriteCategories?: Array<{ id: string; name: string; icon?: string; color?: string }>;
  favoritePacks?: any[];
  onOpenFavoritesManagement?: () => void;
  barcodeInput: string;
  setBarcodeInput: (val: string) => void;
  onBarcodeSubmit: (e?: React.FormEvent) => void;
  searchQuery: string;
  setSearchQuery: (val: string) => void;
  onSettleSale: (paidAmount?: number) => void;
  onSuspendSale: () => void;
  onOpenSuspended: () => void;
  suspendedCount: number;
  onSelectCustomer: () => void;
  selectedCustomerName: string;
  autoPrintReceipt: boolean;
  onToggleAutoPrint: () => void;
  onOpenDiscount: () => void;
  discount: number;
  discountType: 'percent' | 'amount';
  onOpenFreeProduct?: () => void;
  onOpenReturns?: () => void;
  returnMode?: boolean;
  onOpenCustomize: () => void;
  wholesaleMode?: boolean;
  toggleWholesaleMode?: () => void;
  priceTier?: '1' | '2' | '3' | '4';
  onSelectPriceTier?: (tier: '1' | '2' | '3' | '4') => void;
  onSaveAsProforma?: () => void;
  onSaveAsOrder?: () => void;
  onNewOrder?: () => void;
  onOpenSalesHistory?: () => void;
  invoiceNumber?: string | number;
  formatMoney: (amount?: number | null) => string;
  currency?: string;
  userName?: string;
  storeName?: string;
  isSessionOpen?: boolean;
  isSalePending?: boolean;
  onToggleFullscreen?: () => void;
  isFullscreen?: boolean;
  onNavigateBack: () => void;
  onOpenKeypad?: () => void;
  onOpenKeypadForQty?: (item: CartItem) => void;
  onOpenKeyboard?: () => void;
  onOpenAddProduct?: () => void;
  selectedCustomer?: string;
  customers?: Customer[];
  /** Global (POSPage-level) modal state — Esc closes those before navigating back */
  isAnyModalOpen?: boolean;
  onCloseAllModals?: () => void;
}
