org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true

# Network timeout resilience
systemProp.http.socketTimeout=120000
systemProp.http.connectionTimeout=120000
systemProp.https.socketTimeout=120000
systemProp.https.connectionTimeout=120000

# New architecture
newArchEnabled=false
hermesEnabled=true

# React Native
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
reactNativeEnableHermes=true
