import {
  Package,
  Printer,
  ShoppingCart,
  Zap,
  Smartphone,
  QrCode,
  Lock,
  Cpu,
} from 'lucide-react';
import type { SystemFeature } from '../types';

export const SUPPORT_FEATURES: SystemFeature[] = [
  {
    id: 'feat-packages-favs',
    category: 'العبوات والمفضلة (تصميم 5)',
    title: 'إدارة المفضلة والعبوات المخصصة لتصميم 5',
    badge: 'بيع سريع وموجه',
    desc: 'شاشة مفضلة مستقلة مخصصة لبيع العبوات والكراتين فقط لتسريع حركة المحل ومنع خلط التجزئة مع الجملة.',
    highlights: ['عرض العبوات فقط', 'استقلالية تامة عن تصنيفات التجزئة', 'أداة تعديل العبوات الحية', 'تسعير سريع وفوري'],
    icon: Package,
    iconColor: 'text-amber-700 dark:text-amber-400',
    iconBg: 'bg-amber-100 dark:bg-amber-500/15 border-amber-300 dark:border-amber-500/30',
    route: '/pos/advanced',
  },
  {
    id: 'feat-wholesale-print',
    category: 'الطباعة الحرارية وفاتورة الجملة',
    title: 'نظام الطباعة المزدوج وفاتورة الجملة الآلية',
    badge: 'طباعة ذكية',
    desc: 'توجيه الطباعة تلقائياً: فواتير عادية للأسعار س1/س2/س4، وفاتورة جملة مخصصة مفصلة العبوات عند البيع بسعر س3.',
    highlights: ['توجيه تلقائي حسب نوع السعر', 'فاتورة جملة بتفاصيل الكراتين', 'دعم طابعات 80mm و 58mm', 'معاينة فورية وطباعة صامتة'],
    icon: Printer,
    iconColor: 'text-blue-700 dark:text-blue-400',
    iconBg: 'bg-blue-100 dark:bg-blue-500/15 border-blue-300 dark:border-blue-500/30',
    route: '/settings',
  },
  {
    id: 'feat-pos',
    category: 'نقطة البيع (POS) والتصاميم',
    title: 'نقطة البيع المتقدمة (5 تصاميم متخصصة)',
    badge: 'القلب النابض',
    desc: 'واجهة بيع متطورة تدعم 5 أنماط عرض (Classic, Touch Grid, Compact, Split, Terminal 5) لتناسب أي متجر أو مطعم.',
    highlights: ['أزرار العمليات العلوية', 'مؤشرات مالية ملونة', 'دعم الشاشات اللمسية', 'اختصارات F1-F12'],
    icon: ShoppingCart,
    iconColor: 'text-emerald-700 dark:text-emerald-400',
    iconBg: 'bg-emerald-100 dark:bg-emerald-500/15 border-emerald-300 dark:border-emerald-500/30',
    route: '/pos/advanced',
  },
  {
    id: 'feat-quick-pos',
    category: 'نقطة البيع (POS) والتصاميم',
    title: 'نقطة البيع السريع (Quick POS)',
    badge: 'سرعة فائقة',
    desc: 'نمط مسح متواصل ومباشر بالباركود مصمم لمواجهة طوابير الانتظار في السوبرماركت ومحلات البقالة الكبيرة.',
    highlights: ['مسح متكرر لمضاعفة الكمية', 'طباعة فورية', 'حساب الصرف تلقائياً', 'دون لمس الفأرة'],
    icon: Zap,
    iconColor: 'text-amber-700 dark:text-amber-400',
    iconBg: 'bg-amber-100 dark:bg-amber-500/15 border-amber-300 dark:border-amber-500/30',
    route: '/pos/quick',
  },
  {
    id: 'feat-fastify-sync',
    category: 'الهاتف والشبكة والأجهزة',
    title: 'اقتران هواتف بائعي الصالة عبر QR',
    badge: 'مزامنة لاسلكية',
    desc: 'تحويل أي هاتف ذكي لنقطة بيع أو جهاز جرد متنقل عبر مسح رمز QR على شبكة Wi-Fi المحلية على خادم Fastify الداخلي.',
    highlights: ['ربط لحظي بمسح QR', 'منفذ Fastify :3000 محلي', 'جرد وفحص أسعار بالممرات', 'قائمة بيضاء للأجهزة'],
    icon: Smartphone,
    iconColor: 'text-indigo-700 dark:text-indigo-400',
    iconBg: 'bg-indigo-100 dark:bg-indigo-500/15 border-indigo-300 dark:border-indigo-500/30',
    route: '/settings',
  },
  {
    id: 'feat-barcode-bench',
    category: 'الهاتف والشبكة والأجهزة',
    title: 'منصة فحص واختبار قارئ الباركود الحية',
    badge: 'تشخيص العتاد',
    desc: 'بيئة اختبار تفاعلية تقيس زمن استجابة الماسحات الضوئية بالمللي ثانية وتفحص تواجد السلعة في القاعدة مع صوت Beep.',
    highlights: ['تغذية صوتية إلكترونية', 'قياس زمن الاستجابة (ms)', 'فحص الكود بالقاعدة فورياً', 'التحقق من لاحقة Enter'],
    icon: QrCode,
    iconColor: 'text-emerald-700 dark:text-emerald-400',
    iconBg: 'bg-emerald-100 dark:bg-emerald-500/15 border-emerald-300 dark:border-emerald-500/30',
    route: '/settings',
  },
  {
    id: 'feat-security-backup',
    category: 'الأمان والنسخ الاحتياطي',
    title: 'أمان scrypt والنسخ الاحتياطي السريع',
    badge: 'حماية مصرفية',
    desc: 'تشفير كلمات المرور بـ scrypt مع Salt عشوائي، قفل التسجيل الذاتي للغرباء، وتصدير قاعدة البيانات واسترجاعها بضغطة زر.',
    highlights: ['تشفير scrypt الفولاذي', 'حظر التسجيل الذاتي', 'تصدير نسخة مشفرة', 'استرجاع فوري للبيانات'],
    icon: Lock,
    iconColor: 'text-red-700 dark:text-red-400',
    iconBg: 'bg-red-100 dark:bg-red-500/15 border-red-300 dark:border-red-500/30',
    route: '/settings',
  },
  {
    id: 'feat-offline-first',
    category: 'الأمان والنسخ الاحتياطي',
    title: 'معمارية العمل دون إنترنت (Offline-First 100%)',
    badge: 'استمرارية تامة',
    desc: 'يعمل النظام محلياً بالكامل عبر محركي SQLite و Dexie المدمجين، ولا يتوقف البيع أو إصدار الوثائق أبداً عند انقطاع الشبكة.',
    highlights: ['لا يتطلب اتصال إنترنت', 'محرك SQLite صلب', 'واجهة Dexie بدون تأخير', 'استقرار مستمر 24/7'],
    icon: Cpu,
    iconColor: 'text-cyan-700 dark:text-cyan-400',
    iconBg: 'bg-cyan-100 dark:bg-cyan-500/15 border-cyan-300 dark:border-cyan-500/30',
    route: '/pos',
  },
];
