import {
  Package,
  Printer,
  ShoppingCart,
  Zap,
  Smartphone,
  QrCode,
  Lock,
  Cpu,
  Monitor,
  CreditCard,
  FileSpreadsheet,
  FileText,
  SunMoon,
} from 'lucide-react';
import type { SystemFeature } from '../types';

export const SUPPORT_FEATURES: SystemFeature[] = [
  {
    id: 'feat-design6-advanced-terminal',
    category: 'نقطة البيع (POS) والتصاميم',
    title: 'المحطة المتقدمة للمحاسبة السريعة (تصميم 6)',
    badge: 'تصميم 6 الأحدث',
    desc: 'واجهة كاشير هندسية متكاملة بشاشة LED نيون عملاقة، جدول سلة RTL متناسق بدقة، فاحص سلع مستقل (F10)، تعديل سعر مباشر (F4)، لوحة مفضلة 2×8، والوضعين النهاري والليلي.',
    highlights: [
      'شاشة نيون LED عملاقة للوصل والزبون',
      'جدول مبيعات RTL منظم بأعمدة ثابتة',
      'نافذة بحث سلع مستقلة سريعة (F10)',
      'تعديل سعر فوري للسطر المباشر (F4)',
      'لوحة مفضلة وتجزئة 2×8 قابلة للتبديل',
      'تبديل فوري بين الوضعين النهاري والليلي',
    ],
    icon: Monitor,
    iconColor: 'text-cyan-700 dark:text-cyan-400',
    iconBg: 'bg-cyan-100 dark:bg-cyan-500/15 border-cyan-300 dark:border-cyan-500/30',
    route: '/pos/advanced',
  },
  {
    id: 'feat-payment-shortcuts',
    category: 'نقطة البيع (POS) والتصاميم',
    title: 'نظام اختصارات الدفع والتأكيد الفوري (F1-F8 & Enter)',
    badge: 'كاشير بدون ماوس',
    desc: 'معالج اختصارات عالي الأولوية لنافذة الدفع يتيح اختيار وسائل السداد بـ (F1-F4)، والفئات النقدية بـ (F5-F8)، والتأكيد بـ Enter، والإلغاء بـ Esc، وطباعة الوصل بـ P.',
    highlights: [
      'تأكيد الدفع فوراً بـ (Enter / NumpadEnter)',
      'إلغاء وإغلاق نافذة الدفع بـ (Esc)',
      'اختيار وسائل الدفع: نقداً (F1)، بطاقة (F2)، تحويل (F3)، آجل (F4)',
      'فئات نقدية سريعة: بالضبط (F5)، +500 (F6)، +1000 (F7)، +2000 (F8)',
      'طباعة الوصل الحراري فورياً في نافذة النجاح (P / F1)',
    ],
    icon: CreditCard,
    iconColor: 'text-emerald-700 dark:text-emerald-400',
    iconBg: 'bg-emerald-100 dark:bg-emerald-500/15 border-emerald-300 dark:border-emerald-500/30',
    route: '/pos',
  },
  {
    id: 'feat-remote-mobile-scanner',
    category: 'الهاتف والشبكة والأجهزة',
    title: 'الماسح اللاسلكي الذكي عبر كاميرا الهاتف',
    badge: 'مسح عن بُعد',
    desc: 'تحويل أي هاتف ذكي إلى قارئ باركود لاسلكي متصل بالكاشير عبر مسح رمز QR؛ يقرأ السلع بكاميرا الهاتف وتضاف فورياً ومباشرة لسلة الكاشير بالكمية المطلوبة.',
    highlights: [
      'ربط فوري بمسح رمز QR دون كابلات',
      'إضافة مباشرة إلى سلة الكاشير الحية',
      'إشعارات تأكيد وإصدار صوت تنبيهي فوري',
      'دعم مسح عدة بائعين في الصالة في نفس الوقت',
    ],
    icon: Smartphone,
    iconColor: 'text-indigo-700 dark:text-indigo-400',
    iconBg: 'bg-indigo-100 dark:bg-indigo-500/15 border-indigo-300 dark:border-indigo-500/30',
    route: '/settings',
  },
  {
    id: 'feat-supplier-invoice-parser',
    category: 'المخزون والعائلات',
    title: 'محلل ومستورد فواتير الموردين من PDF',
    badge: 'أتمتة المشتريات',
    desc: 'محرك ذكي لقراءة وتفريغ فواتير الموردين ومذكرات الشراء من ملفات PDF آلياً، واستخراج الأسماء والكميات وأسعار التكلفة وتحديث المخزون دون إدخال يدوي.',
    highlights: [
      'استيراد مباشر من ملفات PDF الموردين',
      'استخراج تلقائي للأصناف والأسعار والكميات',
      'مطابقة ذكية مع سلع المخزون الحالية',
      'توفير ساعات العمل وتلافي أخطاء الإدخال',
    ],
    icon: FileText,
    iconColor: 'text-purple-700 dark:text-purple-400',
    iconBg: 'bg-purple-100 dark:bg-purple-500/15 border-purple-300 dark:border-purple-500/30',
    route: '/suppliers',
  },
  {
    id: 'feat-smart-excel-export',
    category: 'التقارير والمبيعات',
    title: 'تصدير إكسل الذكي المتقدم (Excel / XLSX Export)',
    badge: 'تقارير احترافية',
    desc: 'تصدير بيانات المبيعات، سجلات الجرد، حركات الصندوق، وقوائم العملاء والموردين إلى جداول Excel منسقة بخلايا محاسبية ورؤوس واضحة للتحليل والمحاسبة.',
    highlights: [
      'تصدير فوري بصيغة XLSX متوافقة مع Excel و Sheets',
      'تنسيق تلقائي للتواريخ والمبالغ بالدينار الجزائري',
      'تصدير المبيعات، المخزون، وحسابات الديون',
      'جاهزية تامة للأرشفة والتدقيق المحاسبي',
    ],
    icon: FileSpreadsheet,
    iconColor: 'text-emerald-700 dark:text-emerald-400',
    iconBg: 'bg-emerald-100 dark:bg-emerald-500/15 border-emerald-300 dark:border-emerald-500/30',
    route: '/reports',
  },
  {
    id: 'feat-packages-favs',
    category: 'العبوات والمفضلة (تصميم 5)',
    title: 'إدارة المفضلة والعبوات المخصصة لتصميم 5',
    badge: 'بيع سريع وموجه',
    desc: 'شاشة مفضلة مستقلة مخصصة لبيع العبوات والكراتين فقط لتسريع حركة المحل ومنع خلط التجزئة مع الجملة.',
    highlights: ['عرض العبوات فقط', 'استقلالية تامة عن تصنيفات التجزئة', 'أداة تعديل العبوات الحية', 'تسعير سريع وفوري'],
    icon: Package,
    iconColor: 'text-amber-700 dark:text-amber-400',
    iconBg: 'bg-amber-100 dark:bg-amber-500/15 border-amber-300 dark:border-amber-500/30',
    route: '/pos/advanced',
  },
  {
    id: 'feat-wholesale-print',
    category: 'الطباعة الحرارية وفاتورة الجملة',
    title: 'نظام الطباعة المزدوج وفاتورة الجملة الآلية',
    badge: 'طباعة ذكية',
    desc: 'توجيه الطباعة تلقائياً: فواتير عادية للأسعار س1/س2/س4، وفاتورة جملة مخصصة مفصلة العبوات عند البيع بسعر س3.',
    highlights: ['توجيه تلقائي حسب نوع السعر', 'فاتورة جملة بتفاصيل الكراتين', 'دعم طابعات 80mm و 58mm', 'معاينة فورية وطباعة صامتة'],
    icon: Printer,
    iconColor: 'text-blue-700 dark:text-blue-400',
    iconBg: 'bg-blue-100 dark:bg-blue-500/15 border-blue-300 dark:border-blue-500/30',
    route: '/settings',
  },
  {
    id: 'feat-pos',
    category: 'نقطة البيع (POS) والتصاميم',
    title: 'نقطة البيع المتطورة (6 تصاميم متخصصة)',
    badge: 'القلب النابض',
    desc: 'واجهة بيع متطورة تدعم 6 أنماط عرض متخصصة (Classic, Touch Grid, Compact, Split Velocity, Terminal 5, Advanced Terminal 6) لتلائم أي نشاط تجاري.',
    highlights: ['6 تصاميم مخصصة لكل نشاط', 'مؤشرات مالية حية', 'دعم شاشات اللمس والباركود', 'اختصارات كاملة F1-F12'],
    icon: ShoppingCart,
    iconColor: 'text-emerald-700 dark:text-emerald-400',
    iconBg: 'bg-emerald-100 dark:bg-emerald-500/15 border-emerald-300 dark:border-emerald-500/30',
    route: '/pos/advanced',
  },
  {
    id: 'feat-quick-pos',
    category: 'نقطة البيع (POS) والتصاميم',
    title: 'نقطة البيع السريع (Quick POS)',
    badge: 'سرعة فائقة',
    desc: 'نمط مسح متواصل ومباشر بالباركود مصمم لمواجهة طوابير الانتظار في السوبرماركت ومحلات البقالة الكبيرة.',
    highlights: ['مسح متكرر لمضاعفة الكمية', 'طباعة فورية', 'حساب الصرف تلقائياً', 'دون لمس الفأرة'],
    icon: Zap,
    iconColor: 'text-amber-700 dark:text-amber-400',
    iconBg: 'bg-amber-100 dark:bg-amber-500/15 border-amber-300 dark:border-amber-500/30',
    route: '/pos/quick',
  },
  {
    id: 'feat-fastify-sync',
    category: 'الهاتف والشبكة والأجهزة',
    title: 'اقتران هواتف بائعي الصالة عبر خادم Fastify',
    badge: 'مزامنة لاسلكية',
    desc: 'ربط هواتف الصالة بخادم Fastify المحلي على المنفذ :3000 للجرد والاستعلام ونقل السلع دون الحاجة لأجهزة طرفية باهظة.',
    highlights: ['ربط لحظي بمسح QR', 'منفذ Fastify :3000 محلي', 'جرد وفحص أسعار بالممرات', 'قائمة بيضاء للأجهزة'],
    icon: Smartphone,
    iconColor: 'text-indigo-700 dark:text-indigo-400',
    iconBg: 'bg-indigo-100 dark:bg-indigo-500/15 border-indigo-300 dark:border-indigo-500/30',
    route: '/settings',
  },
  {
    id: 'feat-barcode-bench',
    category: 'الهاتف والشبكة والأجهزة',
    title: 'منصة فحص واختبار قارئ الباركود الحية',
    badge: 'تشخيص العتاد',
    desc: 'بيئة اختبار تفاعلية تقيس زمن استجابة الماسحات الضوئية بالمللي ثانية وتفحص تواجد السلعة في القاعدة مع صوت Beep.',
    highlights: ['تغذية صوتية إلكترونية', 'قياس زمن الاستجابة (ms)', 'فحص الكود بالقاعدة فورياً', 'التحقق من لاحقة Enter'],
    icon: QrCode,
    iconColor: 'text-emerald-700 dark:text-emerald-400',
    iconBg: 'bg-emerald-100 dark:bg-emerald-500/15 border-emerald-300 dark:border-emerald-500/30',
    route: '/settings',
  },
  {
    id: 'feat-security-backup',
    category: 'الأمان والنسخ الاحتياطي',
    title: 'أمان scrypt والنسخ الاحتياطي السريع',
    badge: 'حماية مصرفية',
    desc: 'تشفير كلمات المرور بـ scrypt مع Salt عشوائي، قفل التسجيل الذاتي للغرباء، وتصدير قاعدة البيانات واسترجاعها بضغطة زر.',
    highlights: ['تشفير scrypt الفولاذي', 'حظر التسجيل الذاتي', 'تصدير نسخة مشفرة', 'استرجاع فوري للبيانات'],
    icon: Lock,
    iconColor: 'text-red-700 dark:text-red-400',
    iconBg: 'bg-red-100 dark:bg-red-500/15 border-red-300 dark:border-red-500/30',
    route: '/settings',
  },
  {
    id: 'feat-offline-first',
    category: 'الأمان والنسخ الاحتياطي',
    title: 'معمارية العمل دون إنترنت (Offline-First 100%)',
    badge: 'استمرارية تامة',
    desc: 'يعمل النظام محلياً بالكامل عبر محركي SQLite و Dexie المدمجين، ولا يتوقف البيع أو إصدار الوثائق أبداً عند انقطاع الشبكة.',
    highlights: ['لا يتطلب اتصال إنترنت', 'محرك SQLite صلب', 'واجهة Dexie بدون تأخير', 'استقرار مستمر 24/7'],
    icon: Cpu,
    iconColor: 'text-cyan-700 dark:text-cyan-400',
    iconBg: 'bg-cyan-100 dark:bg-cyan-500/15 border-cyan-300 dark:border-cyan-500/30',
    route: '/pos',
  },
];
