export interface Types {
  Product: {
    id: string;
    name: string;
    productName?: string;
    price?: number;
    retailPrice?: number;
    retail_price?: number;
    sale_price2?: number;
    salePrice2?: number;
    sale_price3?: number;
    salePrice3?: number;
    wholesalePrice?: number;
    wholesale_price?: number;
    wholesaleMinQty?: number;
    wholesale_min_qty?: number;
    wholesaleUnitName?: string;
    wholesale_unit_name?: string;
    invoicePrice?: number;
    invoice_price?: number;
    profitMargin?: number;
    profit_margin?: number;
    averagePrice?: number;
    average_price?: number;
    weight?: number;
    packageSize?: string;
    package_size?: string;
    location?: string;
    discount?: number;
    quantity?: number;
    qty?: number;
    unit?: string;
    barcode?: string;
    sku?: string;
    category?: string;
    categoryId?: string;
    category_id?: string;
    status?: string;
    lowStockThreshold?: number;
    costPrice?: number;
    cost_price?: number;
    purchasePrice?: number;
    purchase_price?: number;
    taxRate?: number;
    tax_rate?: number;
    allowNegativeStock?: boolean | number;
    allow_negative_stock?: boolean | number;
    quickSale?: boolean | number;
    quick_sale?: boolean | number;
    customPrices?: any[];
    custom_prices?: string | any[];
    image?: string;
    imageUrl?: string;
    image_url?: string;
  };
  Pack: {
    id: string;
    name: string;
    barcode?: string;
    price?: number;
    packPrice?: number;
    pack_price?: number;
    packType?: string;
    pack_type?: string;
    unitName?: string;
    unit_name?: string;
    piecesCount?: number;
    pieces_count?: number;
    minWholesaleQty?: number;
    min_wholesale_qty?: number;
    items: string | any[];
    status?: string;
    is_active?: number;
    createdAt?: string;
    created_at?: string;
    updatedAt?: string;
    updated_at?: string;
  };
  Sale: {
    id: string;
    number: string;
    date: string;
    docType: string;
    type: string;
    items: any[];
    subtotal: number;
    discount: number;
    discountType: string;
    tvaAmount: number;
    total: number;
    paymentMethod: string;
    customerId: string;
    customerName: string;
    amountPaid: number;
    status: string;
    soldBy: string;
  };
  Customer: {
    id: string;
    name: string;
    phone: string;
    email?: string;
    address?: string;
    tax_id?: string;
    customerType?: string;
    customer_type?: string;
    rc?: string;
    nif?: string;
    nis?: string;
    art?: string;
    credit_limit?: number;
    creditLimit?: number;
    balance: number;
    status?: string;
    notes?: string;
    createdAt?: string;
    created_at?: string;
  };
  Supplier: { id: string; name: string; phone: string; balance: number };
  User: { id: string; username: string; name: string; pin: string; role: string; status: string };
}

export type Product = Types['Product'];
export type Pack = Types['Pack'];
export type Sale = Types['Sale'];
export type Customer = Types['Customer'];
export type Supplier = Types['Supplier'];
export type User = Types['User'];
export type CartItem = {
  productId: string;
  name: string;
  qty: number;
  unitPrice: number;
  lineTotal: number;
  promoName?: string;
};
